"""Chromium DOM checks. Loads HTML with set_content; Storage is explicitly simulated.
Not a native file/HTTP persistence or production backend test.
Run: CHROMIUM_PATH=/usr/bin/chromium python 高保真/tests/rag_introduction_test.py
"""
from pathlib import Path
import base64, json, os, re
from playwright.sync_api import sync_playwright
ROOT = Path(__file__).resolve().parents[1]
OUT = Path(os.environ.get('RAG_TEST_OUTPUT', str(ROOT / 'tests/artifacts/rag-introduction')))
OUT.mkdir(parents=True, exist_ok=True)
HTML = (ROOT / 'rag-introduction.html').read_text()
HTML = HTML.replace('<script src="assets/rag-introduction.js" defer></script>', '<script>' + (ROOT / 'assets/rag-introduction.js').read_text() + '</script>')
HTML = HTML.replace('<link rel="stylesheet" href="assets/article-v2.css">', '<style>' + (ROOT / 'assets/article-v2.css').read_text() + '</style>')
HTML = HTML.replace('src="assets/rag-reading-cover.webp"', 'src="data:image/webp;base64,' + base64.b64encode((ROOT / 'assets/rag-reading-cover.webp').read_bytes()).decode() + '"')
KEY = 'zhiye:rag-introduction:v1:'
checks = []
errors = []
def check(name, condition):
    checks.append({'name': name, 'passed': bool(condition)})
    assert condition, name

def load(context, seed=None, fail=False):
    page = context.new_page()
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.on('dialog', lambda d: d.accept())
    store = json.dumps(seed or {}, ensure_ascii=False)
    mock = '<script>window.__store=' + store + ';Object.defineProperty(window,"localStorage",{configurable:true,value:{getItem:k=>Object.hasOwn(__store,k)?__store[k]:null,setItem:(k,v)=>{' + ('throw new DOMException("Quota exceeded","QuotaExceededError");' if fail else '__store[k]=String(v);') + '},removeItem:k=>delete __store[k]}});</script>'
    page.set_content(HTML.replace('<head>', '<head>' + mock, 1), wait_until='load')
    page.wait_for_timeout(50)
    return page

with sync_playwright() as pw:
    browser = pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH', '/usr/bin/chromium'), args=['--no-sandbox','--disable-dev-shm-usage'])
    context = browser.new_context(viewport={'width':1586,'height':992}, device_scale_factor=1.5, accept_downloads=True, reduced_motion='reduce')
    page = load(context)
    page.set_default_timeout(2500)
    check('Three main chapters', page.locator('.article-section').count() == 3)
    check('Three TOC entries', page.locator('.toc a').count() == 3)
    check('Five topic groups', page.locator('.topic').count() == 5)
    check('Original cover loads', page.locator('.article-cover img').evaluate('(e)=>e.naturalWidth') == 768)
    check('Original desktop columns', page.locator('.workspace').evaluate('(e)=>getComputedStyle(e).gridTemplateColumns') == '320px 838px 320px')
    check('All fragment references resolve', page.evaluate('''()=>Array.from(document.querySelectorAll('a[href^="#"]')).every(a=>document.getElementById(a.getAttribute('href').slice(1)))'''))
    check('Unique DOM ids', page.evaluate('''()=>{const a=Array.from(document.querySelectorAll('[id]')).map(e=>e.id);return a.length===new Set(a).size}'''))
    for width in [320,360,375,390,414,480,640,768,820,821,1024,1100,1101,1280,1440,1586,1920]:
        page.set_viewport_size({'width':width,'height':900})
        check(f'No horizontal overflow at {width}px', page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.set_viewport_size({'width':1586,'height':992})
    page.screenshot(path=str(OUT / 'desktop.png'))
    page.locator('.topic summary').first.click()
    check('Topic collapses', page.locator('.topic').first.get_attribute('open') is None)
    page.locator('.topic summary').first.click()
    page.locator('[data-search="article"]').click()
    page.locator('#search-input').fill('备份')
    check('Article search finds supporting chapters', page.locator('.search-result').count() >= 2)
    page.keyboard.press('ArrowDown')
    check('Search supports keyboard focus', page.evaluate('document.activeElement.classList.contains("search-result")'))
    page.keyboard.press('Enter')
    check('Search closes after navigation', not page.locator('#search-dialog').evaluate('(e)=>e.open'))
    page.keyboard.press('Control+k');page.locator('#search-input').fill('不存在的特定文章zz')
    check('Search empty state', page.locator('.dialog-empty').count() == 1)
    page.keyboard.press('Escape')
    page.locator('.toc a[href="#what-is-rag"]').click();page.wait_for_timeout(80)
    check('TOC tracks chapter', page.locator('.toc a[aria-current="location"]').get_attribute('href') == '#what-is-rag')
    check('Reading progress advances', int(page.locator('.progress-track').get_attribute('aria-valuenow')) > 0)
    page.locator('#what-is-rag .rag-flow').scroll_into_view_if_needed()
    page.screenshot(path=str(OUT / 'content.png'))
    page.locator('#theme-toggle').click()
    check('Dark mode enabled', page.locator('html').get_attribute('data-theme') == 'dark')
    page.locator('#theme-toggle').click()
    page.locator('[data-back-top]').click();page.wait_for_timeout(50)
    page.locator('#bookmark').click()
    check('Bookmark state updates', page.locator('#bookmark').get_attribute('aria-pressed') == 'true')
    page.locator('[data-collection="bookmarks"]').click()
    check('Bookmark collection shows current article', page.locator('#info-body').inner_text().find('什么是 RAG') >= 0)
    page.keyboard.press('Escape')
    page.locator('[data-preview]').first.click()
    check('Unpublished article clearly marked', '正文尚未接入' in page.locator('#info-body').inner_text())
    page.keyboard.press('Escape')
    page.locator('#question-input').fill('<img src=x onerror=alert(1)> 资料不足怎么办？')
    page.locator('#question-form button[type=submit]').click()
    check('Questions render as plain text', '<img' in page.locator('.discussion-copy').first.inner_text() and page.locator('#discussion-list img').count() == 0)
    check('Question is explicitly not public', '未公开发布' in page.locator('.discussion-item').first.inner_text())
    check('Questions not stored', not any('question' in x for x in page.evaluate('Object.keys(__store)')))
    page.locator('#notes-tab').click()
    page.locator('#note-input').fill('第一条批注：先查资料，再回答。')
    page.locator('#note-form button[type=submit]').click()
    check('Note added', page.locator('.note-item').count() == 1)
    check('Isolated storage namespace', KEY+'notes' in page.evaluate('Object.keys(__store)') and not any(x.startswith('zhiye:article-v2:') for x in page.evaluate('Object.keys(__store)')))
    page.locator('.note-item').get_by_role('button',name='编辑',exact=True).click()
    page.locator('#note-input').fill('更新后的批注')
    page.locator('#save-note').click()
    check('Note edit saved', '更新后的批注' in page.locator('.note-item').inner_text())
    page.locator('.toc a[href="#why-rag"]').click()
    page.evaluate('''()=>{const p=document.querySelector('#why-rag p');const r=document.createRange();r.selectNodeContents(p);const s=getSelection();s.removeAllRanges();s.addRange(r);document.querySelector('#article-body').dispatchEvent(new PointerEvent('pointerup',{bubbles:true}));}''')
    page.wait_for_timeout(50);page.locator('[data-selection="note"]').click()
    check('Selection attaches quote', not page.locator('#note-quote').evaluate('(e)=>e.hidden'))
    page.locator('#note-input').fill('这句话说明了通用知识与项目知识的差别。');page.locator('#save-note').click()
    check('Quote saved with source anchor', page.locator('.note-item blockquote').count() == 1 and page.locator('.note-item a').first.get_attribute('href') == '#why-rag')
    with page.expect_download() as info:
        page.locator('#export-notes').click()
    download=info.value
    export=Path(download.path()).read_text()
    check('Markdown export contains text and quote', '更新后的批注' in export and '原文章节：why-rag' in export)
    seed=page.evaluate('Object.assign({},__store)')
    restored=load(context,seed)
    restored.locator('#notes-tab').click()
    check('Serialized notes restore in a fresh document', restored.locator('.note-item').count() == 2)
    restored.locator('.note-item').first.get_by_role('button',name='删除',exact=True).click()
    check('Confirmed delete removes note', restored.locator('.note-item').count() == 1)
    restored.close()
    page.locator('#note-input').fill('尚未保存的草稿');page.locator('#question-tab').click();page.locator('#notes-tab').click()
    check('Tab switching preserves draft', page.locator('#note-input').input_value() == '尚未保存的草稿')
    page.locator('#note-input').fill('')
    page.locator('.more summary').click();page.locator('.more [data-focus]').click()
    check('Focus mode hides sidebars', not page.locator('#library').is_visible() and not page.locator('#right-rail').is_visible())
    page.locator('.exit-focus').click()
    check('Exit restores layout', page.locator('#library').is_visible() and page.locator('#right-rail').is_visible())
    page.set_viewport_size({'width':390,'height':844});page.locator('[data-back-top]').click();page.wait_for_timeout(80)
    page.screenshot(path=str(OUT / 'mobile.png'))
    for kind in ['library','toc','notes']:
        page.locator(f'.floating-dock [data-drawer="{kind}"]').click()
        check(f'Mobile {kind} drawer opens', page.locator('#drawer').evaluate('(e)=>e.open'))
        check(f'Mobile {kind} drawer contains live DOM', page.locator('#drawer-body > *').count() == 1)
        page.keyboard.press('Escape');page.wait_for_timeout(20)
        check(f'Mobile {kind} restores original DOM', page.locator('.workspace > #library').count() == 1 and page.locator('.workspace > #right-rail').count() == 1)
    page.locator('.floating-dock [data-drawer="toc"]').click()
    page.locator('.toc a[href="#use-cases"]').click();page.wait_for_timeout(80)
    check('Mobile chapter navigation closes drawer', not page.locator('#drawer').evaluate('(e)=>e.open'))
    page.locator('.floating-dock [data-drawer="notes"]').click()
    page.set_viewport_size({'width':1586,'height':992});page.wait_for_timeout(80)
    check('Widening viewport restores right rail', not page.locator('#drawer').evaluate('(e)=>e.open') and page.locator('.workspace > #right-rail').count() == 1)
    broken=load(context,{KEY+'notes':'{invalid'})
    broken.locator('#notes-tab').click();broken.locator('#note-input').fill('不能覆盖旧数据');broken.locator('#save-note').click()
    check('Corrupt storage remains intact', broken.evaluate('__store["'+KEY+'notes"]') == '{invalid')
    check('Corruption warning shown', not broken.locator('#storage-warning').evaluate('(e)=>e.hidden'))
    broken.close()
    quota=load(context,fail=True);quota.locator('#notes-tab').click();quota.locator('#note-input').fill('暂存笔记');quota.locator('#save-note').click()
    check('Write failure keeps note in memory', quota.locator('.note-item').count() == 1)
    check('Write failure does not claim saved', '只暂存' in quota.locator('#toast').inner_text())
    quota.close()
    before=page.evaluate('Object.assign({},__store)')
    page.evaluate('window.dispatchEvent(new StorageEvent("storage",{key:null}))')
    page.locator('#notes-tab').click();page.locator('#note-input').fill('冲突后的笔记');page.locator('#save-note').click()
    check('Cross-tab change blocks stale overwrite', page.evaluate('Object.assign({},__store)') == before)
    check('No JavaScript exceptions', not errors)
    browser.close()
report={'checks':checks,'passed':sum(c['passed'] for c in checks),'total':len(checks),'errors':errors,'mode':'set_content with simulated Storage; no native persistence / backend / deployment verification'}
(OUT/'test-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print(json.dumps({'passed':report['passed'],'total':report['total'],'errors':errors},ensure_ascii=False))
